name: lint-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        # Install project
        run: |
          make install
        # Add environment variables
        env:
          CI: true
      - name: Run linter
        # Run Linter
        run: |
          make lint